
workflows:
  fyne_ios:
    name: Fyne iOS Build
    environment:
      xcode: latest
      vars:
        APP_ID: com.kristus310.fynetest
    scripts:
      - name: Install Go and Fyne
        script: |
          brew install go
          go install fyne.io/tools/cmd/fyne@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          
      - name: Build iOS App
        script: |
          export PATH=$PATH:$(go env GOPATH)/bin
          fyne package -os ios -app-id $APP_ID -icon Icon.png
          
    artifacts:
      - "*.app"