workflows:
  fyne_ios:
    name: Fyne iOS Build
    max_build_duration: 60
    environment:
      vars:
        APP_ID: com.kristus310.fynetest
        APP_NAME: FyneTest
        GO111MODULE: "on"
      xcode: latest
    scripts:
      - name: Install Go
        script: brew install go

      - name: Install Fyne CLI
        script: |
          go install fyne.io/tools/cmd/fyne@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Build iOS Project
        script: |
          export PATH=$PATH:$(go env GOPATH)/bin
          cd $CM_PROJECT_DIR
          fyne package --target ios --id $APP_ID --name $APP_NAME --icon Icon.png

      - name: Build IPA
        script: |
          cd ios
          xcodebuild -project $APP_NAME.xcodeproj -scheme $APP_NAME -configuration Release -sdk iphoneos

    publishing:
      scripts:
        - name: Publish IPA
          script: echo "IPA will be available in artifacts"
